# VCenter info goes here
vcenter: sc3-vc-01-vsk-04.pez.vmware.com
vcuserid: "administrator@vsphere.local"
vcpassword: "j>QPDtzNT;m6J8p}x,bB"
node_datacenter: Datacenter
node_cluster: Cluster

workload_vc: 192.168.6.50
workload_vc_uid: "administrator@vsphere.local"
workload_vc_pwd: "VMware1!"

# NSX Manager info goes here
nsxmgr_hostname: pacific-nsx-ua6 
nsx_datastore: LUN-NFS
nsx_network: "DPortGroup-Priv11"
nsxmgr: 192.168.6.54
nsx_subnet_mask: 255.255.255.0
nsx_gateway: 192.168.6.1
nsx_dns: 192.168.6.1
nsx_ntp: 10.192.2.5
nsx_domain_name: env6.lab.local
userid: admin
password: "VMware1!VMware1!"
nsx_ova: 'C:\Users\Administrator\Downloads\GA_Bits\GA_Bits\nsx-unified-appliance-3.0.0.0.0.15946739.ova'

# NSX Edge info goes here
edge_hostname: pacific-nsx-edge6-new 
edge_datastore: LUN-NFS
edge_network: "DPortGroup-Priv11"
edge_tep_network: "DPortGroup-TEP11"
edge_ip: 192.168.6.56
edge_subnet_mask: 255.255.255.0
edge_gateway: 192.168.6.1
edge_dns: 192.168.6.1
edge_ntp: 10.192.2.5
edge_domain_name: env6.lab.local
edge_userid: admin
edge_password: "VMware1!VMware1!"
edge_ova: 'C:\Users\Administrator\Downloads\GA_Bits\GA_Bits\nsx-edge-3.0.0.0.0.15946012.ova'

#Edge IP Pool info goes here
edge_ip_pool_start_ip: 192.168.11.20
edge_ip_pool_end_ip: 192.168.11.30
edge_ip_pool_def_gw: 192.168.11.1
edge_ip_pool_def_cidr: 192.168.11.0/24
edge_tep_vlan: 15
#ESX Host IP Pool info goes here
host_ip_pool_start_ip: 192.168.12.20
host_ip_pool_end_ip: 192.168.12.30
host_ip_pool_def_gw: 192.168.12.1
host_ip_pool_def_cidr: 192.168.12.0/24
host_tep_vlan: 16

#Transport zone info goes here. Use defaults if possible. 
#Defaults are  -
#tz_vlan: nsx-vlan-transportzone
#tz_overlay: nsx-overlay-transportzone
#Uncomment to use your own values
tz_vlan:  TZ-VLAN
tz_overlay: TZ-Overlay

edge_cluster: Edge-Cluster-01

#TO Config goes here
segment: WCP-Segment
segment_vlanids:
  - 0
t0_name: WCP-T0-Gateway
t0_gateway_ip: 192.168.6.57
t0_gateway_cidr: 24
t0_gateway_static_routename: "WCP-Static-Route"
t0_gateway_static_routenw: "0.0.0.0/0"
t0_gateway_static_routeaddr: 192.168.6.1
