# VCenter info for deployment of NSX Manager and Edge 
vcenter: 192.168.100.222
vcuserid: "administrator@vsphere.local"
vcpassword: "VMware1!"
node_datacenter: pacific-dc
node_cluster: pacific-cluster

# Compute Manager vCenter for ESXi hosts to run NSX 
workload_vc: 192.168.100.222
workload_vc_uid: "administrator@vsphere.local"
workload_vc_pwd: "VMware1!"

# NSX Manager info goes here
nsxmgr_hostname: nsx-auto-mgr
nsx_datastore: 222-local-500
nsx_network: "Management-100"
nsxmgr: 192.168.100.224
nsx_subnet_mask: 255.255.255.0
nsx_gateway: 192.168.100.1
nsx_dns: 10.173.13.90
nsx_ntp: time.vmware.com
nsx_domain_name: env6.tpmlab.local
userid: admin
password: "VMware1!VMware1!"
nsx_ova: '/Users/kraustvmware.com/Downloads/nsx-unified-appliance-3.1.0.0.0.17107171.ova'

# NSX Edge info goes here
edge_hostname: nsx-auto-edge
edge_datastore: 222-local-500
edge_network: "Management-100"
edge_tep_network: "Edge-VTEP-102"
edge_ip: 192.168.100.224
edge_subnet_mask: 255.255.255.0
edge_gateway: 192.168.100.1
edge_dns: 10.173.13.90
edge_ntp: time.vmware.com
edge_domain_name: env6.tpmlab.local
edge_userid: admin
edge_password: "VMware1!VMware1!"
edge_ova: '/Users/kraustvmware.com/Downloads/nsx-edge-3.1.0.0.0.17107177.ova'

#Edge IP Pool info goes here
edge_ip_pool_start_ip: 192.168.200.51
edge_ip_pool_end_ip: 192.168.200.54
edge_ip_pool_def_gw: 192.168.200.1
edge_ip_pool_def_cidr: 192.168.200.0/24
edge_tep_vlan: 102
#ESX Host IP Pool info goes here
host_ip_pool_start_ip: 192.168.103.51
host_ip_pool_end_ip: 192.168.103.59
host_ip_pool_def_gw: 192.168.103.1
host_ip_pool_def_cidr: 192.168.103.0/24
host_tep_vlan: 103

#Transport zone info goes here. Use defaults if possible. 
#Defaults are  -
tz_vlan: nsx-vlan-transportzone
tz_overlay: nsx-overlay-transportzone
#Uncomment to use your own values
#tz_vlan:  TZ-VLAN
#tz_overlay: TZ-Overlay

edge_cluster: Edge-Cluster-01

#TO Config goes here
segment: WCP-Segment
segment_vlanids:
  - 100
t0_name: WCP-T0-Gateway
t0_gateway_ip: 192.168.100.251
t0_gateway_cidr: 24
t0_gateway_static_routename: "WCP-Static-Route"
t0_gateway_static_routenw: "0.0.0.0/0"
t0_gateway_static_routeaddr: 192.168.100.1
